shared-version = true
consolidate-commits = true
tag-prefix = ""
tag-name = "v{{ version }}"
tag-message = "Release v{{ version }}"
pre-release-commit-message = "chore: release v{{ version }}"
push = false
