name = "fob-cloudflare-worker-rust-example"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-16"

[build]
command = "cargo install -q worker-build && worker-build --release"

# Development settings
[env.dev]
vars = { ENVIRONMENT = "development" }

# Production settings
[env.production]
vars = { ENVIRONMENT = "production" }

